### ISSUE TITLE
服务端如何配置？

### ISSUE THREAD

**Issue by acoffeeworld** [liyuanhong/ChatClient#1]
如题   求服务端的配置

**Comment by liyuanhong** [comment]
不需要配置服务端，点击启动服务，按钮文字变红色，服务器自动启动，地址为本机地址+端口号
如：192.168.1.111:3000
客户端通过输入服务器的地址，连接后就可以由服务器转发消息相互通信了

**Comment by liyuanhong** [comment]
不需要配置服务端，点击启动服务，按钮文字变红色，服务器自动启动，地址为本机地址+端口号
如：192.168.1.111:3000
客户端通过输入服务器的地址，连接后就可以由服务器转发消息相互通信了
